### ISSUE TITLE
Port to Vercel

### ISSUE THREAD

**Issue by seveibar** [tscircuit/add-pr-comment-proxy#2]
Port this to vercel so we can deploy it for tscircuit

/bounty $20

Please prove that your port works somehow, the main point of this issue is so that I can just run `vc` and not have to validate everything manually

**Comment by melmathari** [comment]
/attempt #2

<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cm3un0zsd0005l103wzqbkdu2/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
